// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hSc-CsyVnMgm3kcLVwj0ZSm6lCxHDoE',
    appId: '1:694017786252:web:ff1ca960e1aeb694ead6a9',
    messagingSenderId: '694017786252',
    projectId: 'mobilegrounda',
    authDomain: 'mobilegrounda.firebaseapp.com',
    storageBucket: 'mobilegrounda.appspot.com',
    measurementId: 'G-YXH7MFZZZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTPyru8q_1h6u7mfN1huaHFnDjwc1YSI',
    appId: '1:694017786252:android:ab9f6f6642b640c7ead6a9',
    messagingSenderId: '694017786252',
    projectId: 'mobilegrounda',
    storageBucket: 'mobilegrounda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqM1i20rHrXeFbWGykG9sJDriPvRKrTA',
    appId: '1:694017786252:ios:c246bb89d0830bdfead6a9',
    messagingSenderId: '694017786252',
    projectId: 'mobilegrounda',
    storageBucket: 'mobilegrounda.appspot.com',
    iosBundleId: 'com.example.mobileFlutterGrounda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqM1i20rHrXeFbWGykG9sJDriPvRKrTA',
    appId: '1:694017786252:ios:c246bb89d0830bdfead6a9',
    messagingSenderId: '694017786252',
    projectId: 'mobilegrounda',
    storageBucket: 'mobilegrounda.appspot.com',
    iosBundleId: 'com.example.mobileFlutterGrounda',
  );
}
